# Generated by Django 3.0.4 on 2020-04-06 23:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
