# Generated by Django 3.0.6 on 2020-05-16 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200509_2055'),
        ('announcement', '0013_announcement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.UserProfile'),
        ),
    ]
