# Generated by Django 3.0.6 on 2020-05-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0016_auto_20200517_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='userprofil',
        ),
    ]
