# Generated by Django 3.0.6 on 2020-05-16 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0018_announcement_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='profile',
        ),
    ]
