# Generated by Django 3.0.6 on 2020-05-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0020_announcement_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='profile',
        ),
    ]
