# Generated by Django 3.0.4 on 2020-05-11 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200511_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
        ),
    ]
