# Generated by Django 3.0.6 on 2020-05-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200513_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.RemoveField(
            model_name='content',
            name='type',
        ),
        migrations.DeleteModel(
            name='CImages',
        ),
    ]
